# template for mruby -->
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "**/mruby/**/*"
    - "build/**/*"
    - "vendor/**/*"

Style/CollectionQuerying:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "test/**/*.rb"
# <-- end

Metrics/AbcSize:
  Max: 25

#Metrics/CyclomaticComplexity:
#  Max: 10

Metrics/MethodLength:
  Max: 30
